apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: taskflow-ingress

spec:
  ingressClassName: nginx

  rules:
  - http:
      paths:

      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80

      - path: /api/tasks
        pathType: Prefix
        backend:
          service:
            name: task-service
            port:
              number: 80

      - path: /swagger/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80

      - path: /swagger/tasks
        pathType: Prefix
        backend:
          service:
            name: task-service
            port:
              number: 80